export const RELAY_ABI = [
  "function platformOwner() view returns (address)",
  "function platformReserve() view returns (uint256)",
  "function parcelCount() view returns (uint256)",
  "function parcels(uint256) view returns (address sender,address recipient,uint256 price,uint8 status,uint16 currentHop,uint256 createdAt,uint256 lastActionAt)",
  "function pointsAvailable(address) view returns (uint256)",
  "function carrierCount(uint256) view returns (uint256)",
  "function carrierAt(uint256,uint256) view returns (address)",
  "function photoHashCount(uint256) view returns (uint256)",
  "function monthlyDisputeCount(address,uint256) view returns (uint256)",
  "function pendingRefunds(address) view returns (uint256)",
  "function postParcel(address recipient,uint256 price) returns (uint256)",
  "function payForParcel(uint256 parcelId) payable",
  "function acceptLeg(uint256 parcelId)",
  "function initiateHandoff(uint256 parcelId,address expectedIncoming,bytes32 photoHash)",
  "function acknowledgeHandoff(uint256 parcelId,bytes32 photoHash)",
  "function confirmDelivery(uint256 parcelId)",
  "function openDispute(uint256 parcelId)",
  "function resolveDispute(uint256 parcelId,uint16 faultyHop)",
  "function claimPendingRefund()",
  "function topUpReserve() payable",
  "event ParcelPosted(uint256 indexed parcelId,address indexed sender,address indexed recipient,uint256 price)",
  "event ParcelPaid(uint256 indexed parcelId,address indexed recipient,uint256 amount)",
  "event LegAccepted(uint256 indexed parcelId,address indexed carrier,uint16 hop)",
  "event HandoffInitiated(uint256 indexed parcelId,address indexed from,address indexed expectedTo,bytes32 photoHash,uint256 deadline)",
  "event HandoffConfirmed(uint256 indexed parcelId,address indexed from,address indexed to,bytes32 photoHash,uint256 timestamp)",
  "event DeliveryConfirmed(uint256 indexed parcelId,address indexed recipient)",
  "event PaymentReleased(uint256 indexed parcelId,address indexed sender,uint256 senderAmount,uint256 platformFee)",
  "event DisputeOpened(uint256 indexed parcelId,address indexed by)",
  "event DisputeResolved(uint256 indexed parcelId,address indexed faultyCarrier,uint256 pointsDeducted)",
  "event PartialRefund(uint256 indexed parcelId,address indexed sender,uint256 paidNow,uint256 debt)",
  "event RefundClaimed(address indexed user,uint256 amount)",
  "event ReserveToppedUp(address indexed owner,uint256 amount,uint256 newReserve)",
  "event TimeoutTriggered(uint256 indexed parcelId,string timeoutType,address penalized)"
];

export const REP_ABI = [
  "function carriers(address) view returns (uint256 points,uint256 totalEarned,uint256 deliveryCount,uint256 ratingSum,uint256 ratingCount,uint256 disputeCount,uint16 tier,bool isVerified)",
  "function getPoints(address carrier) view returns (uint256)",
  "function getTier(address carrier) view returns (uint16)",
  "function submitRating(address carrier,uint8 note)",
  "function onboardCarrier(address carrier)",
  "event PointsAdded(address indexed carrier,uint256 amount,uint256 newBalance)",
  "event PointsDeducted(address indexed carrier,uint256 amount,uint256 newBalance,uint256 disputeCount)",
  "event CarrierOnboarded(address indexed carrier,uint256 initialPoints)"
];
